jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            apk --no-cache add curl bash
            echo 'This is the delivery pipeline'
      - slack/notify:
          color: '#42e2f4'
orbs:
  slack: circleci/slack@3.4
version: 2.1
workflows:
  your-workflow:
    jobs:
      - build