version: 2.1

orbs:
  slack: circleci/slack

jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - slack/approval:
          message: "This is a custom approval message" # Optional: Enter your own message
          mentions: "USERID1,USERID2," # Optional: Enter the Slack IDs of any user or group (sub_team) to be mentioned
          color: "#42e2f4" # Optional: Assign custom colors for each approval message
          webhook: "webhook" # Optional: Enter a specific webhook here or the default will use $SLACK_WEBHOOK
  # build:
  #   docker:
  #     - image: alpine:3.7
  #   steps:
  #     - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            apk --no-cache add curl
            curl 'https://xkcd.com/info.0.json'
            echo 'This is the delivery pipeline'
