version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - slack/approval-notification:
          color: "#aa7fcd" # Optional: Enter your own message
          message: "Deployment pending approval" # Optional: Custom approval message
          channel: "CHANNELID" # Optional: If set, overrides webhook's default channel setting
  # build:
  #   docker:
  #     - image: alpine:3.7
  #   steps:
  #     - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            apk --no-cache add curl
            curl 'https://xkcd.com/info.0.json'
            echo 'This is the delivery pipeline'
