jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - slack/notify:
          channel: Eli
          color: '#42e2f4'
          mentions: 'USERID1,USERID2,'
          message: This is a custom message notification
          webhook: webhook
orbs:
  slack: circleci/slack@3.4
version: 2.1
workflows:
  your-workflow:
    jobs:
      - build